functions:
  double getMilitime():
  void print_matrix_1D_float(float *A, int nr_rows_A):
    args:
    - A:
        type: float
        size: 1024
        range: small
    - nr_rows_A:
        type: int
        value: 1024
  void print_matrix_1D_int(int *A, int nr_rows_A):
    args:
    - A:
        type: int
        size: 1024
        range: big
    - nr_rows_A:
        type: int
        value: 1024
  void print_matrix_2D(float **A, int nr_rows_A, int nr_cols_A):
    args:
    - A:
        type: float
        size: 1024x1024
        range: small
    - nr_rows_A:
        type: int
        value: 1024
    - nr_cols_A:
        type: int
        value: 1024
  void matrix_mult(float**A,float**B,float**C,int m,int n,int k):
    args:
    - A:
        type: float
        size: 1024x1024
        range: big
    - B:
        type: float
        size: 1024x1024
        range: big
    - C:
        type: float
        size: 1024x1024
        range: output
    - m:
        type: int
        value: 1024
    - n:
        type: int
        value: 1024
    - k:
        type: int
        value: 1024
  void find_row_min(float**C,int m,int n,int k,int*row_min_array):
    args:
    - C:
        type: float
        size: 1024x1024
        range: big
    - m:
        type: int
        value: 1024
    - n:
        type: int
        value: 1024
    - k:
        type: int
        value: 1024
    - row_min_array:
        type: int
        size: 1024
        range: output
